#!/usr/bin/env bash

hc() { herbstclient "$@"; }
export -f hc

export TERMINAL=alacritty
export LAUNCHER=dmenu_run

hc emit_hook reload

# Execute configs

./keybinds
./theme
./misc

# Autostart

~/.fehbg
# picom &
