#!/usr/bin/env bash

hc() { herbstclient "$@"; }
export -f hc

export TERMINAL=alacritty
export LAUNCHER=/home/rain/dev/dotfiles/config/rofi/bin/launcher_ribbon

hc emit_hook reload

# Execute configs
CONFIG=/home/rain/dev/dotfiles/config/hlwm

$CONFIG/keybinds
$CONFIG/theme
$CONFIG/misc

# Autostart

~/.fehbg
