#!/usr/bin/env bash

function kb {
    herbstclient keybind $@
}

Mod=Mod4

# Reset all keybinds before loading

hc keyunbind --all

## Herbstluftwm management

kb $Mod-Shift-q quit
kb $Mod-Shift-r reload

## Client management

# Close client
kb $Mod-Shift-c close

# Change Focus
kb $Mod-h focus left
kb $Mod-j focus down
kb $Mod-k focus up
kb $Mod-l focus right

# Move client
kb $Mod-Shift-h shift left
kb $Mod-Shift-j shift down
kb $Mod-Shift-k shift up
kb $Mod-Shift-l shift right

# Terminal and launcher

kb $Mod-Return spawn $TERMINAL
kb $Mod-d      spawn $LAUNCHER

## Frame management

# Split frame

kb $Mod-u             split bottom 0.5
kb $Mod-o             split right  0.5
kb $Mod-Control-space split explode # Turns all clients into separate frames in a given frame

# Resizing frames

resizestep=0.02

kb $Mod-Control-h resize left  +$resizestep
kb $Mod-Control-j resize down  +$resizestep
kb $Mod-Control-k resize up    +$resizestep
kb $Mod-Control-l resize right +$resizestep

# Remove frame

kb $Mod-r remove

## Layouting (in a given frame)

kb $Mod-s floating   toggle
kb $Mod-f fullscreen toggle

kb $Mod-p pseudotile toggle

# Cycle through layouts

hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

## Workspace/tag management

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        kb "$Mod-$key" use_index "$i"
        kb "$Mod-Shift-$key" move_index "$i"
    fi
done

## Mouse

hc mouseunbind --all

hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize
hc mousebind $Mod-Button2 zoom

## Misc

# Menus
kb $Mod-m spawn ~/dev/dotfiles/config/rofi/bin/android_mpd
kb $Mod-Shift-p spawn ~/dev/dotfiles/config/rofi/bin/android_powermenu
kb $Mod-Shift-s spawn ~/dev/dotfiles/config/rofi/bin/android_screenshot
